/**
 * Release pre-flight: verify the built dist/ before uploading to the Chrome
 * Web Store. Run after `npm run build`:
 *
 *   npm run build && npm run preflight
 *
 * Checks:
 *   - dist/manifest.json exists and has a version
 *   - CSP connect-src has no `*.workers.dev` wildcard (prod must pin one origin)
 *   - host_permissions is exactly the expected allowlist (CLOB + builder
 *     relayer + Polygon RPC — the latter two added for in-app sell/redeem)
 *   - no known-burned secret is baked into any shipped file
 *   - manifest.json's `key` still hashes to the extension ID the Worker
 *     allowlists (see below) — catches an accidental key regeneration
 *
 * Exit code 0 = pass, 1 = checks failed, 2 = no build to check.
 */
import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { createHash } from 'node:crypto'

const DIST = 'dist'
// The v2.0 secret that was once committed — treated as public forever.
const BURNED_SECRET = '770d0e45222c7fba195e27da296141a2d1be288120e503ee3161a041642e1f6b'

let failures = 0
const ok = (m) => console.log(`  ✓ ${m}`)
const bad = (m) => {
  console.error(`  ✗ ${m}`)
  failures++
}

let manifest
try {
  manifest = JSON.parse(readFileSync(join(DIST, 'manifest.json'), 'utf8'))
} catch {
  console.error('No dist/manifest.json — run `npm run build` first.')
  process.exit(2)
}

console.log('Pre-flight checks on dist/:')

manifest.version ? ok(`manifest version ${manifest.version}`) : bad('manifest.version missing')

const csp = manifest.content_security_policy?.extension_pages ?? ''
if (csp.includes('*.workers.dev')) {
  bad('CSP still contains a *.workers.dev wildcard — set VITE_WORKER_URL for the prod build')
} else {
  ok('CSP has no *.workers.dev wildcard')
}

// Exact allowlist, order-sensitive on purpose: any drift (an added host, a
// dropped one, a typo'd wildcard) must be a conscious edit HERE, reviewed
// together with the manifest change that caused it.
const EXPECTED_HOST_PERMISSIONS = [
  'https://clob.polymarket.com/*', // CLOB REST (orders, books)
  'https://relayer-v2.polymarket.com/*', // builder relayer (sell/redeem)
  'https://polygon.drpc.org/*', // Polygon RPC reads (positions/redeem)
]
const hp = JSON.stringify(manifest.host_permissions ?? [])
if (hp === JSON.stringify(EXPECTED_HOST_PERMISSIONS)) {
  ok(`host_permissions match expected allowlist (${EXPECTED_HOST_PERMISSIONS.length} hosts)`)
} else {
  bad(`host_permissions unexpected: ${hp}`)
}

function* walk(dir) {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name)
    if (e.isDirectory()) yield* walk(p)
    else yield p
  }
}

// Tooling junk must not ship. Wrangler 4.12x auto-generates a wrangler.jsonc
// next to package.json and writes a resolved copy INTO the assets directory
// it thinks it is deploying — which, run from the wrong directory, is this
// dist/ (hit 2026-08-18). Harmless to the extension, but it would put our
// Worker's config into the public CWS package.
const JUNK = ['wrangler.json', 'wrangler.jsonc', 'wrangler.toml', '.env', '.env.local']
const junkFound = JUNK.filter((f) => {
  try {
    readFileSync(join(DIST, f))
    return true
  } catch {
    return false
  }
})
junkFound.length === 0
  ? ok('no build-tool config leaked into dist')
  : bad(`dist contains files that must not ship: ${junkFound.join(', ')}`)

let leaked = false
for (const f of walk(DIST)) {
  if (!/\.(js|mjs|json|html|css|map)$/.test(f)) continue
  if (readFileSync(f, 'utf8').includes(BURNED_SECRET)) {
    bad(`burned secret found in ${f}`)
    leaked = true
  }
}
if (!leaked) ok('no burned secret baked into dist')

// manifest.json's `key` field deliberately reserves a stable extension ID —
// generated once so the CWS-assigned ID on first publish matches
// ALLOWED_EXTENSION_ID in worker/wrangler.toml (a non-secret, committed
// value). Do NOT strip `key` from the build; that would forfeit the
// reservation and ship a build whose ID the Worker doesn't allowlist. This
// check only catches the key itself silently drifting (e.g. regenerated by
// mistake) — it does not guarantee CWS honors the reservation on a given
// upload (only true for a brand-new item's first-ever publish).
if (manifest.key) {
  const der = Buffer.from(manifest.key, 'base64')
  const hash = createHash('sha256').update(der).digest()
  const id = Array.from(hash.subarray(0, 16))
    .map((b) => String.fromCharCode(97 + (b >> 4)) + String.fromCharCode(97 + (b & 0x0f)))
    .join('')
  let allowed = []
  try {
    const toml = readFileSync(join('worker', 'wrangler.toml'), 'utf8')
    const m = toml.match(/ALLOWED_EXTENSION_ID\s*=\s*"([^"]*)"/)
    allowed = (m?.[1] ?? '').split(',').map((s) => s.trim()).filter(Boolean)
  } catch {
    // wrangler.toml not readable from here — skip silently, not a build blocker
  }
  if (allowed.length === 0) {
    ok(`manifest key resolves to extension ID ${id} (worker/wrangler.toml not checked — no ALLOWED_EXTENSION_ID found)`)
  } else if (allowed.includes(id)) {
    ok(`manifest key resolves to extension ID ${id}, matches ALLOWED_EXTENSION_ID`)
  } else {
    bad(`manifest key resolves to extension ID ${id}, which is NOT in worker/wrangler.toml's ALLOWED_EXTENSION_ID (${allowed.join(', ')}) — Worker will 401 this build`)
  }
}

// Confirm .env.local's build-time secrets actually got baked into dist, not
// silently substituted as empty strings (Vite's `import.meta.env.VITE_X ?? ''`
// pattern builds "successfully" either way — a build run against a blank or
// half-filled .env.local would pass every check above and every unit test,
// then fail at runtime with wc_project_id_missing / builder_code_not_configured
// the first time a real user tries to connect a wallet or place an order).
// Skipped when .env.local doesn't exist — CI's build sets these directly as
// step-scoped env vars instead (see .github/workflows/ci.yml's "Build
// extension (with CI-stub env)"), not a checked-in file, and the CSP check
// above already covers the worker-URL case for that path.
let envLocal
try {
  envLocal = readFileSync('.env.local', 'utf8')
} catch {
  envLocal = null
}
if (envLocal) {
  const distText = [...walk(DIST)]
    .filter((f) => /\.(js|mjs|json|html)$/.test(f))
    .map((f) => readFileSync(f, 'utf8'))
    .join('\n')
  for (const key of ['VITE_BUILDER_CODE', 'VITE_WC_PROJECT_ID']) {
    const m = envLocal.match(new RegExp(`^${key}=(.+)$`, 'm'))
    const value = m?.[1]?.trim()
    if (!value) {
      bad(`${key} is empty or missing in .env.local`)
    } else if (!distText.includes(value)) {
      bad(`${key} from .env.local was not found baked into dist — build may predate this .env.local, or picked up a different value`)
    } else {
      ok(`${key} baked into dist`)
    }
  }
} else {
  console.log('  (skipped .env.local-baked-config check — no .env.local present, e.g. CI)')
}

// --- service-worker isolation -----------------------------------------
/**
 * The MV3 service worker must not statically import page-only code.
 *
 * It has no DOM, and React DOM initializes on evaluation by calling
 * `document.createElement('div').setAttribute('oninput', 'return;')`. When a
 * bundler parks a shared module inside the popup or offscreen entry chunk and
 * has the shared chunk import it back, the worker's own graph reaches that
 * chunk, evaluates React, and dies with "Service worker registration failed.
 * Status code: 15". Nothing else notices: the build succeeds, every unit test
 * passes, and the popup just says "loading..." forever because the worker it
 * is messaging never came up.
 *
 * That shipped once already, silently, in the vite 5 -> 8 (rolldown) upgrade.
 * Hence a check on the artifact itself rather than on the config that is
 * supposed to produce it.
 */
function serviceWorkerGraph() {
  const entry = manifest.background?.service_worker
  if (!entry) return null
  const seen = new Set()
  const visit = (file) => {
    if (seen.has(file)) return
    let src
    try {
      src = readFileSync(join(DIST, file), 'utf8')
    } catch {
      return
    }
    seen.add(file)
    const re = /(?:^|[;\s}])(?:import|export)[^'"();]*?from\s*["']([^"']+)["']|(?:^|[;\s}])import\s*["']([^"']+)["']/g
    let m
    while ((m = re.exec(src))) {
      const spec = m[1] ?? m[2]
      if (!spec?.startsWith('.')) continue
      const from = file.includes('/') ? file.slice(0, file.lastIndexOf('/')) : ''
      visit(new URL(spec, `file:///${from}/`).pathname.replace(/^\//, ''))
    }
  }
  visit(entry)
  return seen
}

const swGraph = serviceWorkerGraph()
if (!swGraph) {
  bad('manifest has no background.service_worker — cannot verify worker isolation')
} else {
  const domOnly = [...swGraph].filter((f) => {
    if (f.endsWith('service-worker-loader.js')) return false
    const src = readFileSync(join(DIST, f), 'utf8')
    return /__SECRET_INTERNALS|createRoot\b|react-dom/.test(src)
  })
  if (domOnly.length > 0) {
    bad(
      `service worker statically imports DOM/React code (${domOnly.join(', ')}) — ` +
        'it will fail to register with "Status code: 15" and the popup will hang on "loading..."',
    )
  } else {
    ok(`service worker graph is DOM-free (${swGraph.size} files)`)
  }
}


console.log(failures ? `\nPRE-FLIGHT FAILED (${failures} issue${failures > 1 ? 's' : ''})` : '\nPRE-FLIGHT PASSED')
process.exit(failures ? 1 : 0)
